const actionTypes = {
    CHANGE_HIDDEN_LAYER_1_NEURONS: 'CHANGE_HIDDEN_LAYER_1_NEURONS',
    CHANGE_HIDDEN_LAYER_2_NEURONS: 'CHANGE_HIDDEN_LAYER_2_NEURONS',
    CHANGE_BIAS: 'CHANGE_BIAS',
    CHANGE_TESTING_FREQUENCY: 'CHANGE_TESTING_FREQUENCY',
    CHANGE_LEARNING_RATE: 'CHANGE_LEARNING_RATE',
    CHANGE_MAX_WEIGHTS_VALUE: 'CHANGE_MAX_WEIGHTS_VALUE'
}

export default actionTypes